server:
  port: 80
zuul:
  routes:
    courses:
      path: /courses-management/**
      serviceId: courses-service
    articles:
      path: /articles-management/**
      serviceId: articles-service
    profiles:
      path: /profiles-management/**
      serviceId: profiles-service
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
